### ISSUE TITLE
Eliminate ruby-xslt dependency

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-build-scripts#1]
List of repos which uses `ruby-xslt` 
 - [`metanorma/isodoc`](https://github.com/metanorma/isodoc)
 - [`metanorma/metanorma-m3d`](https://github.com/metanorma/metanorma-m3d)
 - [`metanorma/html2doc`](https://github.com/metanorma/html2doc)
 - [`metanorma/metanorma-csand`](https://github.com/metanorma/metanorma-csand)

Remove `ruby-xslt` installation once it will be removed from repos above

cc @ronaldtse

**Comment by ronaldtse** [comment]
Agree. Thanks for researching into this @CAMOBAP795

**Comment by CAMOBAP795** [comment]
Related issues:
 - https://github.com/metanorma/isodoc/issues/89
 - https://github.com/metanorma/metanorma-m3d/issues/10
 - https://github.com/metanorma/html2doc/issues/21
 - https://github.com/metanorma/metanorma-csand/issues/7

**Comment by ronaldtse** [comment]
@CAMOBAP795 please help proceed with these. Thanks!

**Comment by CAMOBAP795** [comment]
Only https://github.com/metanorma/html2doc/pull/22 left

**Comment by CAMOBAP795** [comment]
Merged waiting for release of those dependencies

**Comment by CAMOBAP795** [comment]
Done https://github.com/metanorma/metanorma-build-scripts/commit/7921f490f810dea8b6bbcefcffc64929befad960
