### ISSUE TITLE
Should we add add 2.6 to CI matrix for all repos

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-build-scripts#18]
@ronaldtse subj

**Comment by ronaldtse** [comment]
Yes indeed! We should add Ruby matrices to all the coding repos. (Ie. Not the document repos) Thanks!

**Comment by CAMOBAP795** [comment]
Cool, I will proceed

**Comment by CAMOBAP795** [comment]
- https://github.com/metanorma/metanorma-build-scripts/pull/19

**Comment by CAMOBAP795** [comment]
Unfortunately [nokogiri bellow 1.10.0 will not work with ruby 2.6 on windows](https://github.com/sparklemotion/nokogiri/releases/tag/v1.10.0). 

For now, we use several gems which restrict update:
 - https://github.com/metanorma/relaton-bib/blob/master/relaton-bib.gemspec#L36
 - https://github.com/metanorma/relaton-iso-bib/blob/master/relaton_iso_bib.gemspec#L38
 - https://github.com/metanorma/iso-bib-item/blob/master/iso-bib-item.gemspec#L34

@ronaldtse @opoudjis @andrew2net @abunashir any objection against version increase?

**Comment by opoudjis** [comment]
iso-bib-item is obsolete; @andrew2net please deprecate it on Github.

@andrew2net maintains the other two gems. I can't imagine there'll be a problem, but that's his call.

**Comment by ronaldtse** [comment]
> any objection against version increase?

As long as the new nokogiri version works on all platforms, we should upgrade. Thanks!

**Comment by CAMOBAP795** [comment]
`relaton-bib`'s tests passed with `nokogiri "~1.10"`

 @opoudjis may I ask you for help with releasing `relaton-bib`, no rush

**Comment by CAMOBAP795** [comment]
Double-check these ones:
 - https://github.com/metanorma/metanorma-standoc/pull/88
 - https://github.com/metanorma/relaton-server-csd/pull/3
 - https://github.com/metanorma/relaton-cli/pull/60
 - https://github.com/metanorma/iso-bib-item/pull/11

 - https://github.com/metanorma/metanorma-cli/pull/102 (keep)

**Comment by opoudjis** [comment]
@CAMOBAP795 Relaton is the responsibility of @andrew2net  , please check in with him.

**Comment by andrew2net** [comment]
> @opoudjis may I ask you for help with releasing `relaton-bib`, no rush

@CAMOBAP795 I just released all `relaton*` gems

**Comment by CAMOBAP795** [comment]
Done
