### ISSUE TITLE
Appveyor doesn't support _trunk out of box

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-build-scripts#2]
Looks like Appbeyor doesn't support `_trunk` out of box, but this can be fixed by https://github.com/MSP-Greg/appveyor_ruby

cc @ronaldtse

**Comment by ronaldtse** [comment]
I don’t think we need to test trunk at this point on AppVeyor.

**Comment by CAMOBAP795** [comment]
@ronaldtse ok, should I close this one or just keep it?

**Comment by ronaldtse** [comment]
Closing now.
