### ISSUE TITLE
travis-ci.com or travis-ci.org?

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-build-scripts#20]
I noticed that for some repositories we run CI on both 
 - travis-ci.com
 - travis-ci.org

Example:
 - https://travis-ci.com/metanorma/homebrew-metanorma/builds
 - https://travis-ci.org/metanorma/homebrew-metanorma/builds

**Comment by ronaldtse** [comment]
@CAMOBAP795 travis-ci.org is transitioning to travis-ci.com. In the future we want to only use travis-ci.com. However, Travis has not enabled the transition between travis-ci.org to travis-ci.com yet. This means we prefer using travis-ci.com over travis-ci.org.

**Comment by CAMOBAP795** [comment]
Thanks for explanation
