### ISSUE TITLE
Move to GH Actions from travis

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#23]
cc @ronaldtse 

 - [x] port travis/appveyor configuration to GH Actions
 - [x] disable travis/appveyor for those repos
 - [x] fix badges

**Comment by CAMOBAP795** [comment]
- [x] https://github.com/metanorma/mn-templates-csd/pull/10 -  issues for windows was discovered
 - [x] https://github.com/metanorma/metanorma-csand/pull/18
 - [x] https://github.com/metanorma/metanorma-acme/pull/11
 - [x] https://github.com/relaton/relaton-models/pull/21
 - [x] https://github.com/relaton/relaton-bib/pull/14
 - [ ] https://github.com/metanorma/mn-samples-ogc/pull/7 - troubles with latexml installation
 - [ ] https://github.com/metanorma/metanorma-standoc/pull/123 - troubles with latexml installation

----

Once those ones will be good, I will start the massive configuration update

**Comment by ronaldtse** [comment]
@CAMOBAP795 regarding LaTeXML problems, you can try to first fix Snap LaTeXML and use the snap inside. The same with chocolatey.

**Comment by CAMOBAP795** [comment]
- chocolatey-latexml will be updated after https://github.com/metanorma/chocolatey-metanorma/pull/39

**Comment by CAMOBAP795** [comment]
Done

Except badges

**Comment by CAMOBAP795** [comment]
@ronaldtse per https://github.com/search?q=org%3Ametanorma+filename%3A.travis.yml&unscoped_q=filename%3A.travis.yml

We still have travis/appveyour configuration in some repos:
 - `mn-samples-*` in `common` directory
 -  https://github.com/metanorma/metanorma-cli/tree/master/templates/base
 - `rfc-*` repos

Should they be moved to GHA too?

**Comment by ronaldtse** [comment]
Yes, please. I already stopped all Travis/AppVeyor projects, so please help migrate any missed ones.

**Comment by ronaldtse** [comment]
> BTW @ronaldtse do we need those common directory, should I just remove whole directory or just replace travis files with github action ones?

Which common directory do you mean?

**Comment by ronaldtse** [comment]
Yes we should update all the mn-templates-* repos to have the new common files. Thanks!

**Comment by ronaldtse** [comment]
Replace the Travis files with GHA files please. The templates are used when users want to create a new document.

**Comment by CAMOBAP** [comment]
PRs prepared 
@ronaldtse please check https://github.com/metanorma/mn-templates-itu/pull/13 if it ok, I will merge the rest too

**Comment by CAMOBAP** [comment]
Done
