### ISSUE TITLE
Update `ghactions-deploy-to-gh-pages.sh` when GHA supports GITHUB_TOKEN deployment

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-build-scripts#27]
https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/true/page/2

**Comment by CAMOBAP795** [comment]
@ronaldtse looks like not actually anymore because of https://github.com/metanorma/metanorma-build-scripts/issues/33 

https://github.com/peaceiris/actions-gh-pages#supported-tokens - support it already

So looks like we can close it

**Comment by ronaldtse** [comment]
Good! Thanks!
