### ISSUE TITLE
Should we add CodeClimate to all repos?

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#28]
https://gist.github.com/jcypret/608731eed983dd46a9e7447791c86cdb

@ronaldtse how do you think about this? 

For ubuntu only flows

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes we should! But this method requires us to add a `secret` per repo. Our CodeClimate account can already access our repos, not sure what's the way to ensure they are added (we previously added them via the UI interface).

**Comment by CAMOBAP** [comment]
@ronaldtse looks like https://github.com/houndci/hound & https://docs.codeclimate.com/ doing pretty much the same https://stackshare.io/stackups/code-climate-vs-hound#

Will we use both or stay with some of them?

**Comment by ronaldtse** [comment]
Hound is much easier to manage. Let’s close this ticket then.
