### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-build-scripts#30]

**Comment by CAMOBAP795** [comment]
- https://github.com/metanorma/ci-master/commit/27393b30ab61ad388a1f041b4de49046d19ae375
 - https://github.com/metanorma/metanorma-build-scripts/commit/8b9a1757368f28daf5175b1c5a04344a46b8d6e3

**Comment by CAMOBAP795** [comment]
@ronaldtse please check

**Comment by ronaldtse** [comment]
Rewrote READMEs. Closing.
