### ISSUE TITLE
Trigger only modified workflow

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#32]
### Problem

For now, when we change specific GHA workflow file all flows will be triggered

### Solution 

Use https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#excluding-paths to run only changed flow

**Comment by CAMOBAP** [comment]
@ronaldtse let me know how do you think regarding this https://github.com/metanorma/metanorma-build-scripts/commit/18006ec88d89f0b8430a6a91cb0e8ce68a76035f

I think it makes sense to add it to all repositories, to minimize unwanted CI runs

**Comment by ronaldtse** [comment]
Great idea @CAMOBAP , fully agree. Please proceed with it!

**Comment by CAMOBAP** [comment]
Fixed, will be updated on next cimas run
