### ISSUE TITLE
Clean up the gh-pages branch entirely on deployment

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-build-scripts#33]
"""
I'm thinking that we should always clean up the gh-pages branch entirely on deployment

There's no need to carry the gh-pages history

https://github.com/peaceiris/actions-gh-pages looks good to use
"""

**Comment by CAMOBAP795** [comment]
- Sounds like a solution https://stackoverflow.com/a/9254257/902217

**Comment by ronaldtse** [comment]
@CAMOBAP795 I think we only need to turn this option on:

https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan

There's no need to use the suggestion on the SO post.

**Comment by CAMOBAP795** [comment]
Blocked by https://github.com/metanorma/metanorma-linux-setup/issues/23 I will check it first

**Comment by CAMOBAP795** [comment]
Tested on https://github.com/metanorma/mn-samples-itu/runs/542358495?check_suite_focus=true looks great

I will propagate this to other repos

**Comment by ronaldtse** [comment]
Thanks! Feel free to close this when done.

**Comment by CAMOBAP795** [comment]
Two repos left:
 - https://github.com/metanorma/mn-samples-mpfa/pull/19
 - https://github.com/metanorma/mn-samples-ietf/pull/8

**Comment by CAMOBAP795** [comment]
Done
