### ISSUE TITLE
gem install unf_ext failed on windows

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-build-scripts#34]
https://github.com/metanorma/mn-samples-itu/pull/68/checks?check_run_id=522010507 & all mn-samples-* repos

Kind of known issue https://github.com/knu/ruby-unf_ext/issues/52

I will check what we can do about this

```
make failed, exit code 2

Gem files will remain installed in
C:/hostedtoolcache/windows/Ruby/2.5.7/x64/lib/ruby/gems/2.5.0/gems/unf_ext-0.0.7.6
for inspection.
Results logged to
C:/hostedtoolcache/windows/Ruby/2.5.7/x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/unf_ext-0.0.7.6/gem_make.out

An error occurred while installing unf_ext (0.0.7.6), and Bundler cannot
continue.
Make sure that `gem install unf_ext -v '0.0.7.6' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  metanorma-cli was resolved to 1.2.10.1, which depends on
    metanorma-acme was resolved to 1.4.4, which depends on
      metanorma-standoc was resolved to 1.3.21, which depends on
        relaton-iev was resolved to 0.1.3, which depends on
          relaton was resolved to 0.10.1, which depends on
            relaton-un was resolved to 0.1.0, which depends on
              http-cookie was resolved to 1.0.3, which depends on
                domain_name was resolved to 0.5.20190701, which depends on
                  unf was resolved to 0.1.4, which depends on
                    unf_ext
make: *** [Makefile.win:109: bundle] Error 5
```

**Comment by ronaldtse** [comment]
@CAMOBAP795 thanks for the research. How about in we require relaton-un to use unf_ext 0.0.7.5?

**Comment by CAMOBAP795** [comment]
@ronaldtse nice idea I have tried & it works for 2.4, 2.5 but not for 2.6 because unf_ext@0.0.7.5 require ruby < 2.6

**Comment by ronaldtse** [comment]
How about 0.0.7.4? Some version must have worked since it used to build on Windows?

**Comment by CAMOBAP795** [comment]
@ronaldtse you are right 0.0.7.2 works for all platform so we fixated this in https://github.com/relaton/relaton-un/

I think we can close this because the issue is external, I will fix Gemfile till `relaton-un` in the scope of  https://github.com/metanorma/metanorma-build-scripts/issues/35
