### ISSUE TITLE
Keep only docker configuration for private repos

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#37]
Based on discussion with @ronaldtse

**Comment by CAMOBAP795** [comment]
@ronaldtse full list of private repos is https://github.com/metanorma?q=&type=private&language=

But we used GHA only in two of them:
 - https://github.com/metanorma/mn-samples-nist/pull/14
 - https://github.com/metanorma/iso-10303/pull/20

Should I add GHA to all private repos?

**Comment by ronaldtse** [comment]
> Should I add GHA to all private repos?

Yes please! 

In mn-samples-nist and mn-templates-nist, we want to enable Windows also because Windows compilation is important.

**Comment by CAMOBAP795** [comment]
@ronaldtse two questions:
 - should we remove any workflows except docker in https://github.com/metanorma/mn-native-pdf-nist ?
 - I propose to remove ruby matrix from all samples (documentation) repos, because we use chocolatey, brew & Linux script which installs a specific version of ruby

**Comment by ronaldtse** [comment]
> should we remove any workflows except docker in https://github.com/metanorma/mn-native-pdf-nist ?

I think we need to keep Windows workflow in mn-native-pdf-nist because we want to make sure the NIST stylesheet runs on Windows and Ubuntu.

> I propose to remove ruby matrix from all samples (documentation) repos, because we use chocolatey, brew & Linux script which installs a specific version of ruby

Agree.

> should we have gh-pages publishing for those private repos?

We should keep them in case one day GitHub allows gh-pages for private repos.

**Comment by CAMOBAP795** [comment]
Done

**Comment by CAMOBAP** [comment]
Unfortunately, I cannot check it because we already reached GHA limit, IDK how it's possible today only May 2

@ronaldtse maybe you have access to some dashboard, which show some details about how we spent our time,

**Comment by ronaldtse** [comment]
@CAMOBAP i don't know either. The GHA details are not very visible...

**Comment by CAMOBAP** [comment]
ok, formally the task is done
