### ISSUE TITLE
Remove puppeteer from some repos

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#38]
puppetteer has been supplanted by apache XSL:FO
for:
nist ogc csd iso iec rsd

**Comment by CAMOBAP795** [comment]
Done in https://github.com/metanorma/metanorma-build-scripts/commit/673c13343644630baea94d64df4db3244fdac44f

**Comment by opoudjis** [comment]
Sorry! I've missed:

* csa (which I've told you off band)
* un
* itu

The goal is to get rid of puppeteer completely; the following still use puppeteer:

* m3d
* mpfd
* vsd

@ronaldtse These are surely also candidates for culling.

**Comment by CAMOBAP795** [comment]
np @opoudjis thanks for the update, I will update them too

**Comment by CAMOBAP795** [comment]
@opoudjis @ronaldtse repos bellow still require puppeteer
 - https://github.com/metanorma/metanorma-m3d/pull/37
 - https://github.com/metanorma/metanorma-vsd/pull/22
 - https://github.com/metanorma/metanorma-mpfd/pull/41

Should I update some dependency versions in Gemfile for those repos?

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you disable PDF output for m3d, vsd and mpfd? Then we can get rid of puppeteer.

**Comment by CAMOBAP795** [comment]
@ronaldtse if we talk in the scope of those PRs which listed above to disable PDF we will need to modify tests, to me it looks like the wrong way to solve.

Because we use cimas, I think we can just postpone update till those processors will really go out of puppeteer

Make sense?

**Comment by ronaldtse** [comment]
I think we should comment out PDF for these flavors. No one uses these flavors for PDF functionality.

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please check this commit https://github.com/metanorma/metanorma-m3d/pull/38/commits/8811235c33fd6c20dc81b81f0454567d88b4a645

Is this what needs to be done?

**Comment by ronaldtse** [comment]
@CAMOBAP795 :  @opoudjis thoughts?

**Comment by CAMOBAP795** [comment]
thanks to @opoudjis, he already reviewed & merge PR's related to this

**Comment by ronaldtse** [comment]
Nice, thanks!

**Comment by CAMOBAP** [comment]
I think we can close this one because all repos where we can remove puppeteer updated

If there is still something missed, feel free to reopen this
