### ISSUE TITLE
Add packed-mn testing on public samples repos

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#41]
Add packed-mn testing on public samples repos  alongside with docker & ruby metanorma

@ronaldtse how do you think, make sense?

**Comment by ronaldtse** [comment]
Makes sense! 👍

**Comment by ronaldtse** [comment]
(As long as it works...) 😓

**Comment by CAMOBAP** [comment]
In fact, we already do this
