### ISSUE TITLE
Try to merge as much configuration as possible in a single yml file

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#44]
cc @ronaldtse

**Comment by ronaldtse** [comment]
Thanks!

**Comment by ronaldtse** [comment]
The goal is to merge the platforms: macOS, Ubuntu, Windows, Docker into a single test workflow.

**Comment by CAMOBAP** [comment]
@ronaldtse as we discussed in one of packed-mn issues, in case if all platforms will be in the same file in case of failure on some platforms it will rerun all platforms 

I propose to freeze this ticker till https://github.community/t/ability-to-rerun-just-a-single-job-in-a-workflow/17234 will be resolved

**Comment by ronaldtse** [comment]
@CAMOBAP agree!

**Comment by CAMOBAP** [comment]
Decided to implement this to simplify configuration management
