### ISSUE TITLE
CI don't triggered on tags

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#49]
Regression after merge all workflows to a single one

**Comment by CAMOBAP** [comment]
I will do 1.3.8 packed-mn release manually

**Comment by CAMOBAP** [comment]
Also, badges weren't updated after merging os workflows to a single workflow, I will do this in the scope of this task also

**Comment by CAMOBAP** [comment]
cc @opoudjis @ronaldtse

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by CAMOBAP** [comment]
Done
