### ISSUE TITLE
Add graphviz to the base build image

### ISSUE THREAD

**Issue by w00lf** [metanorma/metanorma-build-scripts#52]
Currently we have a new macro from https://github.com/metanorma/metanorma-plugin-lutaml gem - lutaml_diagram, this macro render uml diagrams with graphviz `dot` command, so we need this tool in our build and docker images.

**Comment by CAMOBAP** [comment]
Depends on https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1580
