### ISSUE TITLE
Issue related to metanorma setup interface

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-build-scripts#54]
I came this CI failure here - [mn-templates-cc/pull/23/checks](https://github.com/metanorma/mn-templates-cc/pull/23/checks) and looks like it's because of the recently deleted `metanorma setup` interface. Most of the ci configuration still referencing it and that's causing those failures, should we consider removing this from the actions and update all the repos?

//cc: @CAMOBAP, @ronaldtse

**Comment by CAMOBAP** [comment]
> should we consider removing this from the actions and update all the repos?

Yes exactly I will update templates

**Comment by abunashir** [comment]
Perfect, thanks Alex!

**Comment by CAMOBAP** [comment]
Waiting for CI to pass

**Comment by CAMOBAP** [comment]
Merged
