### ISSUE TITLE
Run Cimas to ensure rfc-* workflows work

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-build-scripts#56]
> `cimas-config/cimas.yml` need to be updated too, please let me know if you need help with this

@CAMOBAP could you help run Cimas to check if the rfc-* workflows work? Thanks!

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-build-scripts/issues/55#issuecomment-751420590_

**Comment by CAMOBAP** [comment]
blocked by https://github.com/metanorma/packed-mn/issues/74

**Comment by CAMOBAP** [comment]
Fixed
