### ISSUE TITLE
Error: POST You have triggered an abuse detection mechanism

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#58]
Error: POST https://api.github.com/repos/metanorma/metanorma-ietf/pulls: 403 - You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later. // See: https://docs.github.com/v3/#abuse-rate-limits

I faced with this issue today, this is potential blocker for cimas tool

_To be continued..._

**Comment by CAMOBAP** [comment]
GHA now supports composite steps so finally, we can 'include' some parts of workflow https://github.community/t/is-it-possible-to-reuse-workflow-yaml-to-setup-similar-workflows/17142

Also we can keep many actions in the same repo https://stackoverflow.com/questions/59259783/how-to-combine-two-action-yml-files-in-one-repo

**Comment by ronaldtse** [comment]
@CAMOBAP I still think we should finish up actions-mn instead of using YAML files. Can you help with them?

**Comment by ronaldtse** [comment]
> I faced with this issue today, this is potential blocker for cimas tool

We should probably make Cimas adhere to the rate limiting, later on?

**Comment by CAMOBAP** [comment]
@ronaldtse to be on the same page
 - as far as I understood we can use actions-mn only for "user" repos, we cannot use it for our ruby gems project
 - actions-mn looks working I will start using it for samples repos https://github.com/actions-mn/setup/actions

**Comment by CAMOBAP** [comment]
Composite actions don't support other actions in it (( https://github.com/actions/runner/issues/646

**Comment by CAMOBAP** [comment]
An interesting project appears which https://github.com/mithro/actions-includes but there is still updates on https://github.community/t/support-for-yaml-anchors/16128/60

**Comment by CAMOBAP** [comment]
Not much we can do in the scope of this task except waiting... per https://github.community/t/being-dry-centralized-workflows/16548/7 

> This is on GitHubs roadmap.
