### ISSUE TITLE
Travis Ubuntu install of metanorma is now over 10 minutes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-build-scripts#6]
Typically the script is run like this:

```
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
```

1. There's lots of LaTeXML tests being run
2. Node install takes a long time
3. Compilation of libsass takes a long time
4. The logs become very long (the installation logs should be cut down or at least folded)

**Comment by CAMOBAP795** [comment]
In progress

**Comment by CAMOBAP795** [comment]
> 1. There's lots of LaTeXML tests being run

Fixed in https://github.com/metanorma/metanorma-linux-setup/pull/9

> 2. Node install takes a long time

Unfortunately, I didn't see an option to avoid it 

> Compilation of libsass takes a long time

I see almost on each CI run for different gems

```
Ruby Sass has reached end-of-life and should no longer be used.
* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install
* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme
* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841
```

@ronaldtse  Is this related to us, how exactly we use `libsass`?

> 4. The logs become very long (the installation logs should be cut down or at least folded)

I think it's related to point 1 in the list

**Comment by ronaldtse** [comment]
The `sass` gem deprecation is dealt with here: https://github.com/metanorma/isodoc/issues/100 .

**Comment by ronaldtse** [comment]
And metanorma/isodoc#100 has been resolved.

For libsass, it seems that Xenial contains it (https://launchpad.net/ubuntu/+source/libsass). Or is it too old?

**Comment by CAMOBAP795** [comment]
@ronaldtse BTW https://rubygems.org/gems/sassc/versions already testing prebuild for windows & linux

**Comment by ronaldtse** [comment]
@CAMOBAP795 that's great to know! Please keep an eye on it and incorporate it whenever we can.

**Comment by CAMOBAP795** [comment]
@ronaldtse yep once `sassc` gem will be released it will be 'incorporated' automatically (because `~> 2` version rule) I will just control that CI is green

**Comment by CAMOBAP795** [comment]
Update, `xenial` take 2x less time then `trusty`
 - gems installed 2x faster
 - there is no `sassc` compilation

@ronaldtse do we really need to use nvm for `node`, I think we can speed up the installation if we will  rely on existing nodejs package. how do you think?

**Comment by ronaldtse** [comment]
> do we really need to use nvm for node, I think we can speed up the installation if we will rely on existing nodejs package. how do you think?

@CAMOBAP795 agree:

* add code to check if there is `nodejs` and `npm` from package, and install puppeteer from there.
* if no `nodejs` etc, use `nvm`.

**Comment by CAMOBAP795** [comment]
@ronaldtse ok

**Comment by CAMOBAP795** [comment]
@ronaldtse no valuable speedup, I propose close this task in favor of https://github.com/metanorma/metanorma-linux-setup/issues/13

How do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP795 I agree to use snap instead this script. Let's close this then.
