### ISSUE TITLE
Add CI config for java projects

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#60]
- https://github.com/metanorma/mn2sts
 - https://github.com/metanorma/mn2pdf
 - https://github.com/metanorma/rfc2mn

**Comment by CAMOBAP** [comment]
Unfortunately there is not much common for those repos, I think we can keep them outside of cimas configuration for now

**Comment by opoudjis** [comment]
Note that https://github.com/metanorma/rfc2mn is now archived.
