### ISSUE TITLE
METANORMA_CI_PAT_TOKEN token, Repository not found, OR token has insufficient permissions.

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#61]
- https://github.com/metanorma/metanorma/pull/168#issuecomment-797567992

@ronaldtse could you please check if there is some restrictions where METANORMA_CI_PAT_TOKEN can be used

**Comment by ronaldtse** [comment]
@CAMOBAP the token is indeed available for use in the repository. It allows read/write of repos. Any further permissions needed?

**Comment by CAMOBAP** [comment]
@ronaldtse for some reason it works for `metanrorma-cli` repo https://github.com/metanorma/metanorma/pull/168/checks?check_run_id=2101819540, but doesn't work for other repos, for example, `metanorma` https://github.com/metanorma/metanorma/pull/168/checks?check_run_id=2101819540

I will continue investigation

**Comment by ronaldtse** [comment]
@CAMOBAP maybe this is because there is no secret provided in PRs -- only branches can use those secrets?

**Comment by CAMOBAP** [comment]
@ronaldtse https://github.com/metanorma/metanorma/pull/168/checks?check_run_id=2101819540 - also PR but it works

**Comment by CAMOBAP** [comment]
@ronaldtse could you please run 

`curl -H "Authorization: token ${METANORMA_CI_PAT_TOKEN}" -H 'Accept: application/vnd.github.everest-preview+json' "https://api.github.com/repos/metanorma/metanorma/dispatches" -d '{"event_type": "notify", "client_payload": {}}`

With the actual value of `METANORMA_CI_PAT_TOKEN`, could you please show me the output of this command

**Comment by ronaldtse** [comment]
```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"
}
```

**Comment by CAMOBAP** [comment]
Hmm, @ronaldtse will the same curls works for `metanorma-cli`

`curl -H "Authorization: token ${METANORMA_CI_PAT_TOKEN}" -H 'Accept: application/vnd.github.everest-preview+json' "https://api.github.com/repos/metanorma/metanorma-cli/dispatches" -d '{"event_type": "notify", "client_payload": {}}`

**Comment by ronaldtse** [comment]
@CAMOBAP I just tried again and it works now!

**Comment by CAMOBAP** [comment]
@ronaldtse so both `metanorma` and `metanorma-cli` works for you, right?

**Comment by CAMOBAP** [comment]
Looks like it works now

**Comment by CAMOBAP** [comment]
Hmm, actually it works for all other repositories except `metanorma/metanorma` really strange(

**Comment by ronaldtse** [comment]
@camobap now that you say it, maybe it's about the metanorma/metanorma repo. Indeed, it was lacking access for @metanorma/ci ... now it's in. Thanks for finding that out!

**Comment by CAMOBAP** [comment]
Works now https://github.com/metanorma/metanorma/pull/169/checks?check_run_id=2119463190
