### ISSUE TITLE
ietf related repos timeout

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#63]
### Problem

For IETF related repositories:
 - https://github.com/metanorma/mn-templates-ietf/pull/19
 - https://github.com/metanorma/mn-samples-ietf/runs/2345263413
 - https://github.com/metanorma/homebrew-metanorma/

We often see timeouts like:
```
Reading workgroups from https://tools.ietf.org/wg/...
bundler: failed to load command: metanorma (/Users/runner/work/mn-templates-ietf/mn-templates-ietf/vendor/bundle/ruby/3.0.0/bin/metanorma)
/Users/runner/work/mn-templates-ietf/mn-templates-ietf/vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.3.1/lib/asciidoctor/ietf/validate.rb:48:in `initialize': No such file or directory @ rb_sysopen - https://tools.ietf.org/wg/ (Errno::ENOENT)
	from /Users/runner/work/mn-templates-ietf/mn-templates-ietf/vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.3.1/lib/asciidoctor/ietf/validate.rb:48:in `open'
	from /Users/runner/work/mn-templates-ietf/mn-templates-ietf/vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.3.1/lib/asciidoctor/ietf/validate.rb:48:in `cache_workgroup_ietf'
	from /Users/runner/work/mn-templates-ietf/mn-templates-ietf/vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.3.1/lib/asciidoctor/ietf/validate.rb:75:in `block in cache_workgroup'
	from /Users/runner/work/mn-templates-ietf/mn-templates-ietf/vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.3.1/lib/asciidoctor/ietf/validate.rb:74:in `open'
	from /Users/runner/work/mn-templates-ietf/mn-templates-ietf/vendor/bundle/ruby/3.0.0/gems/metanorma-ietf-2.3.1/lib/asciidoctor/ietf/validate.rb:74:in `cache_workgroup'
...
```

### Proposed solution

This can be fixed by caching ` ~/.metanorma-ietf-workgroup-cache.json` like already done here:
 - https://github.com/metanorma/mn-samples-ietf/blob/master/.github/workflows/generate.yml#L29-L33

One cons: this IETF specific logic and it will be in all other CI configuration

FYI @ronaldtse

**Comment by CAMOBAP** [comment]
The good proposal was made by @ronaldtse here https://github.com/metanorma/metanorma-docker/pull/94#issuecomment-736558819

**Comment by ronaldtse** [comment]
@CAMOBAP this task will be handled here:

* https://github.com/metanorma/metanorma-ietf/issues/156
* https://github.com/metanorma/metanorma-ietf-data/issues/1
