### ISSUE TITLE
Failure in Docker build when using gemfile-to-bundle-add.sh

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-build-scripts#70]
The script at metanorma-build-scripts (https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/gemfile-to-bundle-add.sh) fails if the Gemfile is more complex than a per-line gem. We should use Bundler to parse the Gemfile instead of using bash to parse the gems.

https://github.com/metanorma/iso-10303-2/runs/4185531475?check_suite_focus=true
```
...
Using metanorma-itu 1.4.1
Using metanorma-m3aawg 1.8.1
Using metanorma-ogc 1.5.1
Using metanorma-un 0.7.1
Using metanorma-cli 1.5.1 from https://github.com/metanorma/metanorma-cli.git (at main@c6336dd)
> bundle add stepmod-utils#, path: ~/src/mn/stepmod-utils
Fetching gem metadata from https://rubygems.org/............
Could not find gem 'stepmod-utils#,' in rubygems repository
https://rubygems.org/ or installed locally.
```

From https://github.com/metanorma/iso-10303-2/issues/73

**Comment by ronaldtse** [comment]
Why don't we make this a GH action?

**Comment by ronaldtse** [comment]
Right now the flow looks like this:

<img width="1005" alt="Screenshot 2021-11-12 at 11 08 09 AM" src="https://user-images.githubusercontent.com/11865/141402380-57e8c24f-2f68-4125-b871-751e903de7c0.png">

Perhaps these two lines can be merged into one "setup" (or "development setup") action?

<img width="990" alt="Screenshot 2021-11-12 at 11 08 29 AM" src="https://user-images.githubusercontent.com/11865/141402412-41bb2766-c38d-4aff-bf39-90164ce60dfa.png">

**Comment by CAMOBAP** [comment]
Fixed. Script now drop comments from Gemfile before processing

**Comment by ronaldtse** [comment]
Thanks. Doesn't Bundler have a mechanism to add a Gemfile to a packaged bundle?

**Comment by CAMOBAP** [comment]
@ronaldtse to be honest IDK. The same as IDK why this problem exists at all...
