### ISSUE TITLE
Finally GHA supports workflow include

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-build-scripts#71]
- https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#calling-a-reusable-workflow
 - https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#limitations

We can get rid of cimas tool (run it for the last time)

cc @ronaldtse

**Comment by CAMOBAP** [comment]
Steps:
 - [ ] create includable workflow for all required workflows
 - [ ] update existing repo configuration with cimas for the last time
 - [ ] make cimas obsolete
 - [ ] remove unnecessary cimas configuration

**Comment by ronaldtse** [comment]
Agree @CAMOBAP , thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse may I ask you to doublecheck that our org's secret `METANORMA_CI_PAT_TOKEN` is available for this repo `metanorma/metanorma-build-scripts`?

**Comment by ronaldtse** [comment]
> @ronaldtse may I ask you to doublecheck that our org's secret `METANORMA_CI_PAT_TOKEN` is available for this repo `metanorma/metanorma-build-scripts`?

Yes it is. METANORMA_CI_PAT_TOKEN

**Comment by CAMOBAP** [comment]
@ronaldtse quick update two repos left:
 - https://github.com/metanorma/bipm-si-brochure/pull/166 - it use extra collect command, I think to to implement if better
 - https://github.com/metanorma/mn-samples-mpfa/pull/53 - mpfa processor was removed, I wasn't to configure ci to use the previous metanorma-cli which have it

**Comment by CAMOBAP** [comment]
@ronaldtse I'm not sure about several PRs, may I ask you to review:
 - https://github.com/metanorma/DGGS2ISO-19170/pull/7
 - https://github.com/metanorma/iso-10303-detached-docs/pull/81
 - https://github.com/metanorma/iso-8601-2/pull/10
 - https://github.com/metanorma/iso-8000-100-ed2/pull/7
 - https://github.com/metanorma/iso-8000-51/pull/8
 - https://github.com/metanorma/iso-690/pull/17
 - https://github.com/metanorma/bipm-si-brochure/pull/166

**Comment by ronaldtse** [comment]
@CAMOBAP these are all merged, is this task to be closed? Thanks!

**Comment by CAMOBAP** [comment]
Yep
